### PR TITLE
cleanup and fixes

### PR DESCRIPTION
**Pull request by pabs3**
I can build the code on Linux with these changes.

### CODE REVIEW

**Comment by shayneoneill** [comment]
Noice!

**Comment by shayneoneill** [comment]
The std::placeholders thing was for an aborted attempt to use std::bind to provide partial function application to wrap the callbacks to RTMidi. I ended up abandoning this approach because it was daft and kind of incompatible with C++ methods (I'm bad at C++)  and instead resorted to passing structs with pointers to the good things instead.

**Comment by shayneoneill** [comment]
One issue though, is although this should build on Linux, I actually think it won't work, as RTMidi hasn't got its backend setup correctly to link with the Linux Platform midi drivers. I'll have to come up with a test suite that can detect these. It'll be pretty necessary for further work anyway

**Comment by pabs3** [comment]
Yeah, it doesn't build as-is on Linux because of the macOS stuff.

At some point I'd like to delete the embedded copy of RtMidi and link
to the Debian package of it instead, but that would require some
changes to do something similar on macOS with frameworks or whatever
macOS uses for external dynamically linked libraries.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by shayneoneill** [comment]
The main reason its included is because to run it with DEBUG mode, it needs to be compiled with the required flags.

However at this stage it all kind of just works, so perhaps this could be reverted to the system RTMIDI version. I think the codes in the CMakeList file to do that fairly straight forward. Maybe this needs to be conditional as building installers for Windows and MacOS would require packaging the dynamic versions, but this is perhaps a separate issue.

Probably the more pressing challenge is getting the QT stuff to work without the crappy hardwired directories.

**Pull request merged**
